### ISSUE TITLE
New person to gearswap

### ISSUE THREAD

**Issue by Zach023** [sebyg666/GearInfo#1]
"In order to make my Gearswap files work you will need the files in the Libs Directory and you will need a copy of the globals file that has some required code in order for everything to work."

What files in Libs Directory?
What is globals file?

**Comment by sebyg666** [comment]
if you are new to gearswap, i do not recommend you try to use gearinfo in conjunction with it. go learn how gearswap works, get some luas for your jobs and once you are comfortable with that then incorporating gearinfo into it will make more sense.

**Comment by Zach023** [comment]
I learned gearswap today. I have it setup and working.
